name: 'Baidu Tieba Auto Sign'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 16,22 * * *'

jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    if: >-
      github.event.repository.owner.id == github.event.sender.id ||
      github.event_name == 'schedule'
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai      
      - name: 'Checkout codes'
        uses: actions/checkout@v3
      - name: 'Set python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
      - name: 'Start Sign'
        env:
          BDUSS: ${{ secrets.BDUSS }}
          HOST: ${{ secrets.HOST }}
          FROM: ${{ secrets.FROM }}
          TO: ${{ secrets.TO }}
          AUTH: ${{ secrets.AUTH }}
        run: python main.py
      - name: Chickin Api #签到
        run: | 
          echo -n `date +%Y-%m-%d\ %H:%M:%S`\ -\ >> ./run.log 
          tail run.log #避免日志上传失败丢失日志
      - name: Push log #更新日志
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto-checkin
          branch: main
